# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Bilal Technology Blog
description: Dr Muhammad Bilal is Associate Professor of Big Data and Artificial Intelligence at University of the West of England (UWE) Bristol. Before UWE, he worked as the data engineer, database administrator, data scientist and full-stack software engineer in IT sector. Bilal received a PhD in Big Data Analytics from UWE Bristol. His research transcends knowledge boundaries through effective research leadership and industry engagement for delivering high-impact digital interventions. His research interests cut across databases, big data, artificial intelligence (AI), computer vision, natural language processing, sensor fusion, geospatial analysis/mining and web of data technologies. He has been actively involved in applying emerging techniques in these areas to develop commercial AI products to solve real-life problems in the finance, healthcare and construction industries. This is evidenced by his direct involvement in the successful delivery of £4.4million R&D projects at UWE Big Data Enterprise and Artificial Intelligence Lab (Big-DEAL) in collaboration with leading UK businesses. With over 15 years of research and teaching experience, he has published over 50 papers in highly reputable journals and international conferences.
github_username: jph00

# Email and twitter are optional:
email: muhammad.bilal@uwe.ac.uk
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
